on:
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  status:
    runs-on: ubuntu-latest
    name: Build Rojo Project
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
      - name: Enter Project Directory
        run: cd dist/test/example
      - name: Build
        uses: CompeyDev/rojo-build-action@0.1.4
        with:
          output: model
          type: rbxm
      - name: Commit and push if there are changes
        run: |-
          git diff
          git config --global user.email "hi@devcomp.xyz"
          git config --global user.name "BuildBot"
          git diff --quiet || (git add -u && git commit -m "chore(deploy): build rojo project")
          git push               
