on:
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  status:
    runs-on: ubuntu-latest
    name: Build Rojo Project (Demo)
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
      - name: Enter Project Directory
        run: cd dist/test/example
      - name: Build
        uses: CompeyDev/rojo-build-action@main
        with:
          output: model
          type: rbxm
          working-directory: ./dist/test/example
